apiVersion: v1
kind: Pod
metadata:
  name: supra-test
spec:
  containers:
   - name: mavencontainer
     image: maven:3.5.4-jdk-8-slim
     command: ["sleep", "43200"]
   - name: dockercontainer
     image: docker:20
     command: ["sleep", "43200"]
     volumeMounts:
       - name: docker
         mountPath: /var/run/docker.sock
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
